# Generated by Django 5.2.14 on 2026-05-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='photo',
            new_name='picture',
        ),
    ]
