# Generated by Django 5.2.14 on 2026-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_photo_team_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='teams/pictures/', verbose_name='Photo'),
        ),
    ]
