# Generated by Django 5.2.14 on 2026-05-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_on', 'subject', 'full_name'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
