# Generated by Django 5.2.14 on 2026-05-15 16:42

import django.db.models.deletion
import hitcount.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Marqué comme supprimé')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernières modifications')),
                ('extra_data', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Extra JSON')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('icon', models.ImageField(blank=True, help_text='Téléchargez une icône pour représenter ce service', null=True, upload_to='services/icons/', verbose_name='Icône du service')),
                ('summary', models.CharField(help_text='Un bref résumé (en quelques mots)', max_length=50, verbose_name='Résumé du service')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('obj_created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_on'],
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
