# Generated by Django 5.2.14 on 2026-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, help_text='Téléchargez une image pour illustrer ce service', null=True, upload_to='services/pictures/', verbose_name='Image du service'),
        ),
    ]
