# Generated by Django 5.2.14 on 2026-05-11 18:18

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import hitcount.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Marqué comme supprimé')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernières modifications')),
                ('extra_data', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Extra JSON')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Adresse électronique')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom(s)')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de famille')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nº de téléphone')),
                ('gender', models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('undefined', 'Non défini')], default='undefined', max_length=10, null=True, verbose_name='Sexe')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste/Occupation')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/%Y/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('obj_created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined', 'email', 'first_name', 'last_name', 'gender', 'date_of_birth', 'username'],
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
