"""
    Generated by "django-admin startproject" using Django 5.2.14 and then customized.
"""

import os
from pathlib import Path
from decouple import config as dev_config
from django.utils.translation import gettext_lazy as _

#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                  ROOT CONFIGS               #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
BASE_DIR = Path(__file__).resolve().parent.parent
PRODUCTION_MODE = True



def config(var, data_type=None, default=None):
    value = os.environ.get(key=var, default=default) if PRODUCTION_MODE else dev_config(var, default=default)
    
    if value is None:
        return default
    
    if data_type is bool:
        return str(value).lower() in ("true", "1", "yes", "on")
    
    elif data_type is int:
        try:
            return int(value)
        except ValueError:
            raise ValueError(f"Cannot convert '{var}' into an integer.")
    
    elif data_type is int:
        return str(value)
    
    elif data_type is float:
        try:
            return float(value)
        except ValueError:
            raise ValueError(f"Cannot convert '{var}' into a float.")
    
    elif data_type is list:
        return [item.strip() for item in str(value).split(",")]
    
    return value

DEBUG = True
SECRET_KEY = config("SECRET_KEY", data_type=str)

if PRODUCTION_MODE:
    DEBUG = False

SITE_ID = config("SITE_ID", data_type=int, default=1)
ALLOWED_HOSTS = ["www.biadvisorytech.com", "biadvisorytech.com", "127.0.0.1", "localhost"]
SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]
INTERNAL_IPS = ["127.0.0.1"]
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
WSGI_APPLICATION = "biadvisorytech.wsgi.application"
ROOT_URLCONF = "biadvisorytech.urls"
ADMINS = [
    ("Admin ABI", "contact@biadvisorytech.com")
]

SITE_NAME = config("SITE_NAME", data_type=str, default="ABI")
SITE_PHONE_NUMBER = config("SITE_PHONE_NUMBER", data_type=str, default="+225 01 01 07 60 29")
SITE_EMAIL_ADDRESS = config("SITE_EMAIL_ADDRESS", data_type=str, default="contact@biadvisorytech.com")
SITE_ADDRESS = config("SITE_ADDRESS", data_type=str, default="Abidjan, CI")

_default_site_desc = """
    ABI est une entreprise de conseil en technologie qui aide les entreprises à tirer parti de la technologie 
    pour atteindre leurs objectifs commerciaux.
"""
SITE_DESCRIPTION = config("SITE_DESCRIPTION", data_type=str, default=_default_site_desc)



#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######       INSTALLED APPLICATIONS DEFINITION     #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize", # Added
    "django.contrib.sitemaps", # Added
    "django.contrib.sites", # Added
    "django.contrib.admindocs", # Docuementation of models fields in admin page
    
    # 3rd PARTY APPS
    "storages",
    "hitcount",
    "import_export",
    "django_filters",
    "after_response",
    "django_summernote",
    "django_recaptcha", # ReCaptcha for forms
    "crispy_forms", # styling forms to filter querysets
    "crispy_bootstrap4", # template pack of crispy_forms
    
    # LOCAL APPS
    "accounts.apps.AccountsConfig",
    "contacts.apps.ContactsConfig",
    "core.apps.CoreConfig",
    "newsletter.apps.NewsletterConfig",
    "services.apps.ServicesConfig",
    "teams.apps.TeamsConfig",
    "testimonials.apps.TestimonialsConfig",
    "utilities.apps.UtilitiesConfig",
]




#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######             MIDDLEWARES                     #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serving static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    
    # User detection middleware
    "biadvisorytech.middlewares.auto.CurrentThreadUserMiddleware",
    
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware", # Docuementation of models fields in admin page
    
    
    "htmlmin.middleware.HtmlMinifyMiddleware", # HTML minifier
    "htmlmin.middleware.MarkRequestMiddleware", # HTML minifier
]




#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                 TEMPLATES                   #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                
                # Custom context processors
                "biadvisorytech.context_processors.global_context",
            ],
            # Added builtins
            "builtins": [
                "utilities.templatetags.custom_tags", # custom tags
            ],
        },
    },
]




#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######               DATABASES                     #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
AUTH_USER_MODEL = "accounts.User"






#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######             PASSWORD VALIDATORS             #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 6,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######             INTERNATIONALIZATION            #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
LANGUAGE_CODE = "fr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True



#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######          STATIC & MEDIA FILES CONFIGS       #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "collectstatic/")
MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static/")]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


if PRODUCTION_MODE:
    MEDIA_ROOT = "/home/biadeynh/cdn.biadvisorytech.com/"
    MEDIA_URL = "https://cdn.biadvisorytech.com/"







#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                  EMAIL CONFIGS              #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
EMAIL_BACKEND = "biadvisorytech.services.email.DevEmailBackend" # Only in dev mode
if PRODUCTION_MODE:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST =  config("EMAIL_HOST", data_type=str)
EMAIL_PORT = config("EMAIL_PORT", data_type=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", data_type=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_LOCALTIME = config("EMAIL_USE_LOCALTIME", data_type=bool)

SERVER_EMAIL = f"Server Error - {SITE_NAME} <{EMAIL_HOST_USER}>"
DEFAULT_FROM_EMAIL = f"{SITE_NAME} <{EMAIL_HOST_USER}>"
DEFAULT_EMAIL_RECIPIENTS = [f"{SITE_NAME} <{SITE_EMAIL_ADDRESS}>"] # EMAIL_HOST_USER may not be able to receive emails



#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                  CACHES CONFIGS             #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": f"Site-caching",
    }
}
CACHE_MIDDLEWARE_ALIAS = "default"
CACHE_MIDDLEWARE_SECONDS = 60 * 10 # 10 mins





#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                 SESSIONS CONFIGS            #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 604800 # One week
SESSION_COOKIE_NAME = f"Site-sessionid"
SESSION_COOKIE_SECURE = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = False
if PRODUCTION_MODE:
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True






#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                  HTTPS CONFIGS              #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
if PRODUCTION_MODE:
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"




#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######                LOGGING CONFIGS              #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################
LOGS_FILE_DIR = "logs"
LOGS_FILE_NAME = "logging.log"
MAX_LOG_FILES_BACKUP_COUNT = 30
MAX_LOG_FILE_SIZE = 1024*1024*2. # 2MB
LOG_DIR = os.path.join(BASE_DIR, LOGS_FILE_DIR)
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,  # the dictConfig format version
    "disable_existing_loggers": False,  # retain the default loggers
    
    "handlers": {
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, LOGS_FILE_NAME),
            "maxBytes": MAX_LOG_FILE_SIZE,
            "backupCount": MAX_LOG_FILES_BACKUP_COUNT,
            "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
            "formatter": "verbose",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{asctime}] {levelname} | {message}",
            "style": "{",
        },
    },
    "loggers": {
        "django_components": {
            "level": os.getenv("DJANGO_LOG_LEVEL", "DEBUG"),
            "handlers": ["file"],
        },
        "walie_proj": {
            "handlers": ["file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "": {
            "handlers": ["file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}






#############################################################
#############################################################
#############################################################
#######                                             #########
#######                                             #########
#######           3rd PARTY APPS CONFIGS            #########
#######                                             #########
#######                                             #########
#############################################################
#############################################################
#############################################################



#############################################################
#############################################################
########           DJANGO HTMLMIN CONFIGS         ###########
#############################################################
#############################################################
HTML_MINIFY = True
KEEP_COMMENTS_ON_MINIFYING = False





#############################################################
#############################################################
########            SUMMERNOTE CONFIGS           ############
#############################################################
#############################################################
SUMMERNOTE_THEME = "bs4"
SUMMERNOTE_ALLOWED_MIME_TYPES = [
    "image/jpeg",
    "image/png",
    "image/gif",
    "video/mp4",
    "application/pdf",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
]
SUMMERNOTE_CONFIG = {
    "airMode": False,
    "tabsize": 2,
    "height": 350,
    "width": "100%",
    "focus": True,
    "attachment_require_authentication": True, # Require users to be authenticated for uploading attachments.
    "attachment_absolute_uri": True,
    "attachment_upload_to": "summernote/%Y/%m/",
    "lang": None,
    "attachment_upload_permissions": "summernote.attachment_upload_permission",  # default
    "attachment_upload_whitelist": SUMMERNOTE_ALLOWED_MIME_TYPES,
}




#############################################################
#############################################################
########        DJANGO CRISPY FORM CONFIGS       ############
#############################################################
#############################################################
CRISPY_TEMPLATE_PACK = "bootstrap4"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"




#############################################################
#############################################################
########             RECAPTCHA CONFIGS           ############
#############################################################
#############################################################
RECAPTCHA_PUBLIC_KEY = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
RECAPTCHA_PRIVATE_KEY = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
if PRODUCTION_MODE:
    RECAPTCHA_PUBLIC_KEY = str(config("GOOGLE_RECAPTCHA_PUBLIC_KEY", data_type=str))
    RECAPTCHA_PRIVATE_KEY = str(config("GOOGLE_RECAPTCHA_PRIVATE_KEY", data_type=str))
