# Generated by Django 5.2.14 on 2026-05-15 16:42

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import hitcount.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Marqué comme supprimé')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernières modifications')),
                ('extra_data', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Extra JSON')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nom du client')),
                ('client_position', models.CharField(max_length=255, verbose_name='Position du client')),
                ('client_country', django_countries.fields.CountryField(help_text='Sélectionnez le pays du client', max_length=2, verbose_name='Pays')),
                ('stars', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Étoiles')),
                ('feedback', models.TextField(verbose_name='Feedback du client')),
                ('obj_created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_on'],
                'abstract': False,
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
