# Generated by Django 5.2.14 on 2026-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_picture',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/', verbose_name='Photo du client'),
        ),
    ]
